version: "3.8"
services:
  nest-app:
    build: .
    container_name: nest-app
    ports:
      - "3003:3003"
    working_dir: /app
    command: npm run start:prod  # Inicia o NestJS em produção
    volumes:
      - .:/app  # Monta o código local dentro do container
    environment:
      - NODE_ENV=production

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nest-app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3001"
    depends_on:
      - prometheus
